[package]
name = "road_fighter"
version = "0.1.0"
edition = "2021"

[dependencies]
avian2d = "0.6"
bevy = { version = "0.18", default-features = false, features = [
    "default_app",       # asset loading, logging, state, window 
    "default_platform",  # winit, x11/wayland, default font
    "2d_bevy_render",
] }
rand = "0.10"
thiserror = "2.0"
 
# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
 
# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 'z'  # Optimize for size.
# lto = true
codegen-units = 1
panic = 'abort'
strip = true